name: Umbraco Cloud Preflight

on:
  workflow_call:
    inputs:
      pathToWebsite:
        required: false
        type: string
      csprojFile:
        required: false
        type: string

    secrets:
      umbracoCloudJson:
        required: true
      deployLicenseKey:
        required: true
      formsLicenseKey:
        required: true
        
jobs:
  prepareForDeployment:
    name: Prepare Source for Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable/disable package references in .csproj 
      - name: Update csproj
        working-directory: ${{ inputs.pathToWebsite }}
        shell: pwsh
        run: |
          $content = Get-Content '${{ inputs.csprojFile }}' -Raw
          
          # Enable Umbraco.Cloud.Cms (uncomment)
          $content = $content -replace '(?s)<!--\s*<PackageReference\s+(?=[^>]*Include="Umbraco\.Cloud\.Cms")(?=[^>]*Version="([^"]*)")[^>]*/?>\s*-->', '<PackageReference Include="Umbraco.Cloud.Cms" Version="$1" />'
                    
          # Enable Umbraco.Deploy.Cloud (uncomment)
          $content = $content -replace '(?s)<!--\s*<PackageReference\s+(?=[^>]*Include="Umbraco\.Deploy\.Cloud")(?=[^>]*Version="([^"]*)")[^>]*/?>\s*-->', '<PackageReference Include="Umbraco.Deploy.Cloud" Version="$1" />'
                    
          # Disable Umbraco.Deploy.OnPrem (comment out)
          $content = $content -replace '(?s)<PackageReference\s+(?=[^>]*Include="Umbraco\.Deploy\.OnPrem")(?=[^>]*Version="([^"]*)")[^>]*/?>', '<!-- <PackageReference Include="Umbraco.Deploy.OnPrem" Version="$1" /> -->'
          
          Set-Content '${{ inputs.csprojFile }}' $content
          
      # Create umbraco-cloud.json file from Secret
      - name: Umbraco Cloud Json
        working-directory: ${{ inputs.pathToWebsite }}
        shell: pwsh
        run: set-content 'umbraco-cloud.json' -value '${{ secrets.umbracoCloudJson }}' 

      # Create Deploy license key file from Secret
      - name: Deploy License Key
        working-directory: "${{ inputs.pathToWebsite }}/umbraco/Licenses"
        shell: pwsh
        run: set-content 'umbracoDeploy.lic' -value '${{ secrets.deployLicenseKey }}' 

      # Create Forms license key file from Secret
      - name: Forms License Key
        working-directory: "${{ inputs.pathToWebsite }}/umbraco/Licenses"
        shell: pwsh
        run: set-content 'umbracoForms.lic' -value '${{ secrets.formsLicenseKey }}' 