name: Deploy to Cloud (v2 API) 

on:
  push:
    branches:
      - main
  workflow_dispatch: 

  # Pack and upload the deployment Artifact
  cloud-artifact:
    name: "Prepare and Upload Artifact"
    uses: ./.github/workflows/cloud-artifact.yml
    with:
      pathToWebsite: "src/OpenSourceTest.Site"
      csprojFile: "OpenSourceTest.Site.csproj"
      pathToFrontendClient: "src/OpenSourceTest.MyExtension/Client"
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
      umbracoCloudJson: ${{ secrets.UMBRACO_CLOUD_JSON }}
      deployLicenseKey: ${{ secrets.DEPLOY_LICENSE_KEY }}
      formsLicenseKey: ${{ secrets.FORMS_LICENSE_KEY }}

  # Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: [cloud-artifact]
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      artifactId: ${{ needs.cloud-artifact.outputs.artifactId }}
      targetEnvironmentAlias: stage
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}