name: pipeline

on:
  push:
    branches:
      - main
      - v2-api
    tags:
      - live
  workflow_dispatch: 

jobs:
  set-env:
    name: "Set Target Environment from Branch"
    runs-on: ubuntu-latest
    outputs:
      targetEnv: ${{ steps.set-env-live.outputs.value || steps.set-env-stage.outputs.value }}
    steps:
      - name: Set ENV for live tag
        id: set-env-live
        if: startsWith(github.ref, 'refs/tags/live')
        run: echo "value=live" >> $GITHUB_OUTPUT
      - name: Set ENV for all other occasions (default to stage)
        id: set-env-stage
        if: ${{ !startsWith(github.ref, 'refs/tags/live') }}
        run: echo "value=stage" >> $GITHUB_OUTPUT

  # Get changes from cloud
  # cloud-sync:
  #   name: "Umbraco Cloud Sync"
  #   uses: ./.github/workflows/cloud-sync.yml
  #   secrets:
  #     projectId: ${{ secrets.PROJECT_ID }}
  #     umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
  #   with:
  #     targetEnvironmentAlias: ${{  env.TARGET_ENVIRONMENT_ALIAS }}

  # Pack and upload the deployment Artifact
  cloud-artifact:
    name: "Prepare and Upload Artifact"
    needs: [set-env]
    uses: ./.github/workflows/cloud-artifact.yml
    with:
      pathToWebsite: "src/OpenSourceTest.Site"
      csprojFile: "OpenSourceTest.Site.csproj"
      pathToFrontendClient: "src/OpenSourceTest.MyExtension/Client"
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
      umbracoCloudJson: ${{ secrets.UMBRACO_CLOUD_JSON }}
      deployLicenseKey: ${{ secrets.DEPLOY_LICENSE_KEY }}
      formsLicenseKey: ${{ secrets.FORMS_LICENSE_KEY }}

  # Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: [set-env, cloud-artifact]
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      artifactId: ${{ needs.cloud-artifact.outputs.artifactId }}
      targetEnvironmentAlias: ${{ needs.set-env.outputs.targetEnv }}
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}