name: pipeline

on:
  push:
    branches:
      - main
      - v2-api
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      targetEnv: ${{ steps.set-env-main.outputs.value || steps.set-env-staging.outputs.value }}
    steps:
      - name: Set ENV for main
        id: set-env-main
        if: github.ref == 'refs/heads/main'
        run: echo "value=live" >> $GITHUB_OUTPUT
      - name: Set ENV for v2-api
        id: set-env-staging
        if: github.ref == 'refs/heads/v2-api'
        run: echo "value=stage" >> $GITHUB_OUTPUT

  # Get changes from cloud
  # cloud-sync:
  #   name: "Umbraco Cloud Sync"
  #   uses: ./.github/workflows/cloud-sync.yml
  #   secrets:
  #     projectId: ${{ secrets.PROJECT_ID }}
  #     umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
  #   with:
  #     targetEnvironmentAlias: ${{  env.TARGET_ENVIRONMENT_ALIAS }}

  # Prepare source code ready for deployment
  cloud-predeploy:
    name: "Prepare Source for Deployment"
    needs: set-env
    uses: ./.github/workflows/cloud-predeploy.yml
    with:
      pathToWebsite: "src/OpenSourceTest.Site"
      csprojFile: "OpenSourceTest.Site.csproj"
    secrets:
      umbracoCloudJson: ${{ secrets.UMBRACO_CLOUD_JSON }}
      deployLicenseKey: ${{ secrets.DEPLOY_LICENSE_KEY }}
      formsLicenseKey: ${{ secrets.FORMS_LICENSE_KEY }}

  # Pack and upload the deployment Artifact
  cloud-artifact:
    name: "Prepare and Upload Artifact"
    needs: cloud-predeploy
    uses: ./.github/workflows/cloud-artifact.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: [set-env, cloud-artifact]
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      artifactId: ${{ needs.cloud-artifact.outputs.artifactId }}
      targetEnvironmentAlias: ${{ needs.set-env.outputs.targetEnv }}
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}