name: Deploy to Cloud (v1 API) 

# Trigger when committing to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:

  # Intentionally NOT syncing from Cloud as all patches/updates etc being done manually on GitHub repo

  # Package and Deploy to Umbraco Cloud (without saving the artifact as contains sensitive data)
  cloud-deployment:
    name: "Deploy to Cloud"
    uses: ./.github/workflows/package-and-deploy.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
      umbracoCloudJson: ${{ secrets.UMBRACO_CLOUD_JSON }}
      deployLicenseKey: ${{ secrets.DEPLOY_LICENSE_KEY }}
      formsLicenseKey: ${{ secrets.FORMS_LICENSE_KEY }}
    with:
      pathToWebsite: "src/OpenSourceTest.Site"
      csprojFile: "OpenSourceTest.Site.csproj"