name: test-matt 

# Trigger manually only
on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:

  justCsproj:
    name: Test csproj
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable/disable package references in .csproj 
      - name: Update csproj
        working-directory: "src/OpenSourceTest.Site"
        shell: pwsh
        run: |
          $content = Get-Content 'OpenSourceTest.Site.csproj' -Raw
         
          # Enable Umbraco.Cloud.Cms (uncomment)
          $content = $content -replace '(?s)<!--\s*<PackageReference\s+(?=[^>]*Include="Umbraco\.Cloud\.Cms")(?=.*Version="([^"]*)")[^>]*/?>\s*-->', '<PackageReference Include="Umbraco.Cloud.Cms" Version="$1" />'
                    
          # Enable Umbraco.Deploy.Cloud (uncomment)
          $content = $content -replace '(?s)<!--\s*<PackageReference\s+(?=[^>]*Include="Umbraco\.Deploy\.Cloud")(?=.*Version="([^"]*)")[^>]*/?>\s*-->', '<PackageReference Include="Umbraco.Deploy.Cloud" Version="$1" />'
                    
          # Disable Umbraco.Deploy.OnPrem (comment out)
          $content = $content -replace '(?s)<PackageReference\s+(?=[^>]*Include="Umbraco\.Deploy\.OnPrem")(?=.*Version="([^"]*)")[^>]*/?>', '<!-- <PackageReference Include="Umbraco.Deploy.OnPrem" Version="$1" /> -->'
          
          # Set-Content 'OpenSourceTest.Site.csproj' $content

          echo $content
